services:

  hello-app:
    build: .
    container_name: hello-app

    ports:
      - "3005:3005"

    environment:
      DATA_DIR: /app/data

    volumes:
      - ./data:/app/data

    restart: unless-stopped


  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma

    ports:
      - "3001:3001"

    volumes:
      - ./kuma-data:/app/data

    depends_on:
      - hello-app

    restart: unless-stopped